# Attract To Chat Mod - Server Configuration / Configuração do Servidor

[general]
	# EN: Maximum distance (in blocks) that mobs can "hear" the chat
	# PT-BR: Distância máxima (em blocos) que os mobs podem "ouvir" o chat
	hearingRange = 30.0

	# EN: Minimum cooldown in ticks between mob scans (20 ticks = 1 second)
	# PT-BR: Cooldown mínimo em ticks entre varreduras de mobs (20 ticks = 1 segundo)
	scanCooldownTicks = 20

	# Tempo em segundos para o mob esquecer o ponto da mensagem
    forgetTargetAfterSeconds = 5

	# EN: List of mob IDs that react to chat
	# PT-BR: Lista de IDs dos mobs que reagem ao chat
	enabledEntities = [
		"minecraft:cave_spider",
"minecraft:creeper",
"minecraft:drowned",
"minecraft:endermite",
"minecraft:evoker",
"minecraft:guardian",
"minecraft:hoglin",
"minecraft:husk",
"minecraft:magma_cube",
"minecraft:phantom",
"minecraft:piglin",
"minecraft:piglin_brute",
"minecraft:pillager",
"minecraft:ravager",
"minecraft:shulker",
"minecraft:silverfish",
"minecraft:skeleton",
"minecraft:slime",
"minecraft:spider",
"minecraft:stray",
"minecraft:vex",
"minecraft:vindicator",
"minecraft:witch",
"minecraft:wither_skeleton",
"minecraft:zoglin",
"minecraft:zombie",
"minecraft:zombie_villager",
	]
